version: "2.2"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shopmono
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: psql
    networks:
      - db_network

  backend:
    build:
      context: ./shop_mono
    image: shop_mono/mono:latest
    hostname: shop_mono
    ports:
      - "8080:8080"
    networks:
      - db_network
      - app_network
    depends_on:
      db:
        condition: service_started
    container_name: shopmono

  frontend:
    build:
      context: ./front_mono
    image: front_mono/mono:latest
    hostname: front_mono
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      backend:
        condition: service_started
    container_name: front_mono
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - app_network
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command: --config.file=/etc/prometheus/prometheus.yaml
    ports:
      - 9090:9090
volumes: 
  pgdata:

networks:
  db_network:
    driver: bridge
  app_network:
    driver: bridge